### ISSUE TITLE
Add alias for Visual Studio Code

### ISSUE THREAD

**Issue by SimonIMG** [ividic/dotfiles#1]
Feature request: let's add an alias for Visual Studio Code.

`alias vs='/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron' in .bash_aliases`

I've tested this out and it works, and you can open specific folders like the **subl** alias

**Comment by SimonIMG** [comment]
Although I notice that the Terminal prompt doesn't reset properly. I have to Ctrl + Z to get the prompt again. Unless I specify a folder with . or a folder path. Then I get the prompt back.

**Comment by ividic** [comment]
There is no need - it's already covered by default. Try `code` to open the editor or `code .` to open the current folder in the editor
